// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-EFLt8wcgKct7JjL415X7W0Lwbp8GzFY',
    appId: '1:992525708569:web:5f1ce0f994f3b6b0a22988',
    messagingSenderId: '992525708569',
    projectId: 'gestorabogados',
    authDomain: 'gestorabogados.firebaseapp.com',
    storageBucket: 'gestorabogados.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpMk3ISOjBew3EpO3mX_PZxlye64TturI',
    appId: '1:992525708569:android:117062f71dc891e0a22988',
    messagingSenderId: '992525708569',
    projectId: 'gestorabogados',
    storageBucket: 'gestorabogados.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLtI9t6PFCqO5z1YHUx6Kq4stgQk7_WiE',
    appId: '1:992525708569:ios:e802fa760f63ba0aa22988',
    messagingSenderId: '992525708569',
    projectId: 'gestorabogados',
    storageBucket: 'gestorabogados.firebasestorage.app',
    iosBundleId: 'com.example.appGestionAbogados',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-EFLt8wcgKct7JjL415X7W0Lwbp8GzFY',
    appId: '1:992525708569:web:2b5340975e22d537a22988',
    messagingSenderId: '992525708569',
    projectId: 'gestorabogados',
    authDomain: 'gestorabogados.firebaseapp.com',
    storageBucket: 'gestorabogados.firebasestorage.app',
  );
}
